### ISSUE TITLE
labels on waterways are displayed

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/refill-style-no-labels#1]
at least on some: http://tangrams.github.io/refill-style-no-labels/#15.025/50.0900/19.9517

![selection_009](https://cloud.githubusercontent.com/assets/899988/12292845/23d084d2-b9f0-11e5-9d3c-654b45f07ddc.png)

**Comment by nvkelso** [comment]
Doh! Thanks for noting the error, will have a look at resolving.

**Comment by nvkelso** [comment]
This was resolved in the last release, closing. Sorry for not communicating that earlier!
