### ISSUE TITLE
highway shield labels are still displayed

### ISSUE THREAD

**Issue by thisisaaronland** [tangrams/refill-style-no-labels#3]
See attached. #15/42.2310/-71.0129

![screen shot 2016-04-05 at 16 59 16](https://cloud.githubusercontent.com/assets/12658759/14301841/ddf26006-fb4f-11e5-9614-1eedc1b03684.png)

**Comment by nvkelso** [comment]
Good find!

**Comment by nvkelso** [comment]
Fixed in v2.0.0

**Comment by nvkelso** [comment]
Errr, v3.0.0

**Comment by thisisaaronland** [comment]
![slippy-map-refill-1461284353-drt2pmv3j40p-drt82dn9bgxz](https://cloud.githubusercontent.com/assets/12658759/14727949/351d2a54-07e5-11e6-9b32-ef55b3eca513.png)
