### ISSUE TITLE
airport terminal/gate labels are still displayed

### ISSUE THREAD

**Issue by thisisaaronland** [tangrams/refill-style-no-labels#4]
This affects the `no-labels` versions of cinnabar and zinc, as well.

![screen shot 2016-04-05 at 18 05 03](https://cloud.githubusercontent.com/assets/12658759/14302754/3478a148-fb59-11e5-93ae-3cef84699f49.png)

**Comment by nvkelso** [comment]
Fixed in v2.0.0

**Comment by nvkelso** [comment]
Errr, v3.0.0

**Comment by thisisaaronland** [comment]
![slippy-map-refill-1461284265-9q8vyy9xh0rz-9q8vzpggt5rb](https://cloud.githubusercontent.com/assets/12658759/14727938/088018da-07e5-11e6-8bc5-616e58165a51.png)

It's true!

**Comment by nvkelso** [comment]
Thanks for verifying :) The YAML will be moved onto the mapzen.com CDN "soon".
